CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255)                            NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    email    VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_74165e195b2f7b25de690d14a UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_77584fbe74cc86922be2a3560 UNIQUE (username);




CREATE TABLE IF NOT EXISTS roles
(
    name       varchar(60) not null
    constraint roles_pkey
    primary key,
    privileges varchar(255)
    );


CREATE TABLE IF NOT EXISTS users_roles
(
    user_id   bigint      not null
    constraint fk2o0jvgh89lemvvo17cbqvdxaa
    references users,
    role_name varchar(60) not null
    constraint fkfddtbwrqg5sal9y57yyol7579
    references roles,
    constraint users_roles_pkey
    primary key (user_id, role_name)
    );


CREATE TABLE IF NOT EXISTS files (
                                     id bigserial constraint files_pkey primary key,
                                     content_type varchar(255) not null,
    create_time  timestamp    not null,
    data_type    varchar(255) not null,
    file         oid,
    file_name    varchar(255) not null,
    user_id      bigint
    constraint fkdgr5hx49828s5vhjo1s8q3wdp
    references users
    );


CREATE TABLE IF NOT EXISTS payment
(
    id    bigint       not null
    constraint payment_pkey
    primary key,
    count varchar(255) not null,
    date  timestamp    not null,
    pay   varchar(255) not null
    );



