CREATE TABLE IF NOT EXISTS refreshtoken
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT,
    token       VARCHAR(255)                            NOT NULL,
    expiry_date TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_refreshtoken PRIMARY KEY (id)
);

ALTER TABLE refreshtoken
    ADD CONSTRAINT uc_refreshtoken_token UNIQUE (token);

ALTER TABLE refreshtoken
    ADD CONSTRAINT FK_REFRESHTOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);